const MODELS=["@cf/zai-org/glm-4.7-flash","@cf/google/gemma-4-26b-a4b-it","@cf/meta/llama-3.2-3b-instruct"];
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
const textOf=x=>typeof x==="string"?x:(x?.response||x?.text||x?.result?.response||x?.choices?.[0]?.message?.content||"");
const wc=t=>String(t||"").trim().split(/\s+/).filter(Boolean).length;
const guide=t=>t==="Calm"?"هادئ وواثق ومريح لكن يقظ وغير نعسان، بسرعة طبيعية مائلة للهدوء، بدون مط للكلمات أو خمول":t==="Energetic"?"حماسي وواثق ومباشر، سريع نسبيًا لكن واضح ومن غير صراخ أو مبالغة":"طبيعي وعفوي وواثق، كأن شخصًا حقيقيًا يحكي لصديق";
const rate=t=>t==="Calm"?2.3:t==="Energetic"?2.75:2.55;
async function ask(env,prompt,task){let last="";for(const model of MODELS){try{const out=await env.AI.run(model,{messages:[{role:"user",content:prompt}],max_completion_tokens:task==="script"||task==="durationfix"?950:task==="visuals"?520:task==="voice"?8:350,temperature:task==="visuals"?.18:task==="voice"?.1:.58,stream:false});const t=String(textOf(out)||"").trim();if(t)return{t,model};last=model+": empty"}catch(e){last=String(e?.message||e)}}throw new Error(last||"generation failed")}
export async function generateV13(request,env){
 if(!env.AI?.run)return json({error:"AI binding unavailable"},503);
 let b={};try{b=await request.json()}catch{}
 const task=b.task||"script",topic=String(b.topic||"").trim(),platform=String(b.platform||"TikTok"),tone=String(b.tone||"Natural"),script=String(b.script||"").trim();if(!topic)return json({error:"topic required"},400);
 const duration=Number(b.durationSeconds)||45,current=Number(b.currentDuration)||0,scenes=Math.max(5,Math.min(12,Number(b.sceneCount)||Math.ceil(duration/5.5))),g=guide(tone),target=Math.max(45,Math.round(duration*rate(tone))-13),min=Math.max(40,Math.round(target*.96)),max=Math.round(target*1.08),detailed=topic.length>140;
 let prompt="";
 if(task==="idea")prompt=`اقترح فكرة واحدة قوية لفيديو قصير عن: ${topic}. المنصة: ${platform}. الأسلوب: ${g}. اكتب بالعربية فقط وبدون تعليمات تصوير أو نصوص على الشاشة.`;
 else if(task==="caption")prompt=`اكتب كابشن عربي قصير وجذاب عن: ${topic}. المنصة: ${platform}. الأسلوب: ${g}. أضف 5 هاشتاقات مناسبة. أعد الكابشن فقط.`;
 else if(task==="voice")prompt=`اختر الراوي الأنسب طبيعيًا لهذه القصة من حيث الإحساس وأسلوب الحكي فقط، وأعد كلمة واحدة فقط male أو female.\nالموضوع: ${topic}\nالسكريبت: ${script.slice(0,3200)}`;
 else if(task==="durationfix")prompt=`أعد صياغة النص التالي ليملأ مدة ${duration} ثانية تقريبًا بصوت عربي طبيعي. المدة الحالية حوالي ${current||"غير معروفة"} ثانية. حافظ على كل الأحداث والأسماء والترتيب ولا تحذف أي جزء مهم. اجعل النص بين ${min} و${max} كلمة عربية. إذا كان قصيرًا وسّعه بتفاصيل وحوار ووصف منطقي من نفس القصة فقط. ابدأ بالقصة مباشرة ولا تضف عناوين أو شرحًا تقنيًا.\n${script.slice(0,5200)}`;
 else if(task==="visuals")prompt=`حوّل السكربت التالي إلى ${scenes} لقطات قصصية متتابعة زمنيًا لفيديو رأسي. أعد ${scenes} أسطر إنجليزية فقط، كل سطر عبارة بحث دقيقة من 5 إلى 10 كلمات.\nالموضوع الأصلي: ${topic.slice(0,1800)}\nالسكريبت: ${script.slice(0,4200)}\nكل سطر يجب أن يمثل حدثًا محددًا يحدث فعلًا في القصة وبنفس الترتيب. اذكر الشخص أو الأشخاص + الفعل + المكان + الوقت عند أهميته. حافظ على وصف البطل نفسه عبر اللقطات. ممنوع اللقطات العامة أو الرمزية غير الموجودة في القصة، وممنوع camera أو photographer أو deer أو forest أو typing أو phone إلا إذا كانت موجودة فعلًا في الحدث. لا fashion ولا glamour ولا model ولا posing ولا surreal. بدون ترقيم أو شرح.`;
 else prompt=`اكتب تعليقًا صوتيًا عربيًا طبيعيًا عن: ${topic}. المنصة: ${platform}. الأسلوب: ${g}. المدة المستهدفة للفيديو كاملًا ${duration} ثانية، وسيضاف توقيع ترويجي قصير في النهاية؛ لذلك اكتب متن القصة فقط بين ${min} و${max} كلمة عربية. ${detailed?"النص الذي أدخله المستخدم قصة أو فكرة تفصيلية بالفعل: لا تختصرها ولا تحذف أحداثها؛ حافظ على كل الأحداث والترتيب ووسّعها فقط بتفاصيل طبيعية حتى تصل للمدة المطلوبة.":"حوّل الفكرة إلى قصة أو سرد متكامل ومتماسك، وليس ملخصًا سريعًا."} ابدأ مباشرة بأول جملة من القصة. ممنوع كلمات السكربت أو التعليق الصوتي أو النص أو المقدمة أو المشهد أو أي شرح تقني. لا عناوين ولا ترقيم ولا تعليمات تصوير.`;
 try{let r=await ask(env,prompt,task),t=r.t;if(task==="script"&&wc(t)<min){const e=await ask(env,`وسّع النص التالي مع الحفاظ على كل أحداثه وترتيبه ليصبح بين ${min} و${max} كلمة عربية. لا تلخص ولا تحذف. أضف فقط تفاصيل وحوارًا ووصفًا طبيعيًا من نفس القصة. ابدأ مباشرة بالنص المنطوق بلا عنوان.\n${t}`,"durationfix");if(wc(e.t)>wc(t)){t=e.t;r=e}}return json({text:t,model:r.model,task,words:wc(t)})}catch(e){return json({error:String(e?.message||e)},502)}
}
