"use strict";
(()=>{
  if(window.__RM_MOBILE_AUTO_UI__)return;window.__RM_MOBILE_AUTO_UI__=1;
  let voiceUrl="";
  function mount(){
    if(document.getElementById("rmMobileAuto"))return;
    const s=document.createElement("section");s.id="rmMobileAuto";s.dir="rtl";
    s.innerHTML='<div class="rma-head"><div><b>المحتوى التلقائي</b><small>فكرة ← سكربت ← صوت ← كابشن</small></div><button class="rma-close" type="button">إغلاق</button></div><div class="rma-body"><div class="rma-card"><label>موضوع الفيديو</label><textarea id="rmaTopic" placeholder="مثال: حقائق نفسية غريبة"></textarea><label style="margin-top:10px">المدة</label><select id="rmaDuration"><option value="30">30 ثانية</option><option value="45" selected>45 ثانية</option><option value="60">60 ثانية</option></select><button id="rmaRun" class="rma-run" type="button">إنشاء المحتوى</button><div id="rmaStatus" class="rma-status"></div></div><div class="rma-card"><label>الفكرة</label><div id="rmaIdea" class="rma-out">—</div></div><div class="rma-card"><label>السكربت</label><div id="rmaScript" class="rma-out">—</div></div><div class="rma-card"><label>الصوت</label><div id="rmaVoice" class="rma-out">—</div></div><div class="rma-card"><label>الكابشن</label><div id="rmaCaption" class="rma-out">—</div></div></div>';
    document.body.appendChild(s);
    s.querySelector(".rma-close").addEventListener("click",()=>{s.classList.remove("open");s.style.display="";document.body.style.overflow=""});
    document.getElementById("rmaRun").addEventListener("click",run);
  }
  function open(){mount();const s=document.getElementById("rmMobileAuto");s.classList.add("open");s.style.setProperty("display","block","important");document.body.classList.remove("rm-mobile-open");document.body.style.overflow="hidden";return true}
  async function gen(task,topic,durationSeconds){const r=await fetch("/api/autocontent/generate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({task,topic,durationSeconds})});const j=await r.json();if(!r.ok)throw new Error(j.error||"فشل الإنشاء");return j.text||""}
  function status(t){document.getElementById("rmaStatus").textContent=t}
  async function run(){const topic=document.getElementById("rmaTopic").value.trim();if(!topic)return status("اكتب موضوع الفيديو أولاً");const d=Number(document.getElementById("rmaDuration").value)||45;const btn=document.getElementById("rmaRun");btn.disabled=true;try{status("1/4 إنشاء الفكرة...");document.getElementById("rmaIdea").textContent=await gen("idea",topic,d);status("2/4 كتابة السكربت...");const script=await gen("script",topic,d);document.getElementById("rmaScript").textContent=script;status("3/4 إنشاء الصوت...");try{const vr=await fetch("/api/tts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({text:script,voice:"Kore",style:"egyptian"})});if(!vr.ok)throw new Error("تعذر إنشاء الصوت");const blob=await vr.blob();if(voiceUrl)URL.revokeObjectURL(voiceUrl);voiceUrl=URL.createObjectURL(blob);const a=document.createElement("audio");a.controls=true;a.className="rma-audio";a.src=voiceUrl;const host=document.getElementById("rmaVoice");host.textContent="";host.appendChild(a)}catch(e){document.getElementById("rmaVoice").textContent=e.message}status("4/4 إنشاء الكابشن...");document.getElementById("rmaCaption").textContent=await gen("caption",topic,d);status("اكتمل المحتوى للتجربة")}catch(e){status("خطأ: "+e.message)}finally{btn.disabled=false}}
  function ensureMenu(){const nav=document.querySelector("#rmShellSidebar .rm-shell-nav");if(!nav)return false;let b=nav.querySelector('[data-rm-tool="automation"]');if(!b){const settings=nav.querySelector('[data-rm-tool="settings"]');b=document.createElement("button");b.type="button";b.className="rm-shell-item rm-auto-live-item";b.dataset.rmTool="automation";b.innerHTML='<span class="rm-shell-icon">⚡</span><span class="rm-shell-copy"><b>المحتوى التلقائي</b><small>إنشاء محتوى كامل بالذكاء الاصطناعي</small></span><span class="rm-shell-arrow">‹</span>';if(settings)nav.insertBefore(b,settings);else nav.appendChild(b)}return true}
  function capture(e){const b=e.target?.closest?.('[data-rm-tool="automation"]');if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation?.();open()}
  document.addEventListener("click",capture,true);document.addEventListener("pointerup",capture,true);
  function start(){mount();if(ensureMenu())return;const mo=new MutationObserver(()=>{if(ensureMenu())mo.disconnect()});mo.observe(document.documentElement,{childList:true,subtree:true})}
  document.readyState==="loading"?document.addEventListener("DOMContentLoaded",start):start();window.ReelsAutomation={open};
})();
