const META_KEY='reelsMaker.storyProjects.v38';
const DB_NAME='reelsMaker.storyProjectsMedia.v38',STORE='videos';
const $=id=>document.getElementById(id);
let previewUrl='';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function read(){try{const x=JSON.parse(localStorage.getItem(META_KEY)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function write(x){localStorage.setItem(META_KEY,JSON.stringify(x.slice(0,50)))}
function db(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function putVideo(id,blob){if(!blob?.size)return;try{const d=await db();await new Promise((res,rej)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).put({id,blob,updatedAt:Date.now()});tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});d.close()}catch{}}
async function getVideo(id){try{const d=await db(),v=await new Promise((res,rej)=>{const r=d.transaction(STORE,'readonly').objectStore(STORE).get(id);r.onsuccess=()=>res(r.result?.blob||null);r.onerror=()=>rej(r.error)});d.close();return v}catch{return null}}
async function delVideo(id){try{const d=await db();await new Promise((res,rej)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(id);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});d.close()}catch{}}
function fmt(ts){try{return new Intl.DateTimeFormat('ar-EG',{dateStyle:'medium',timeStyle:'short'}).format(new Date(ts))}catch{return new Date(ts).toLocaleString()}}
function titleOf(p){const idea=String(p.idea||'').trim();if(idea)return idea.slice(0,70);const s=String(p.story||'').trim();return (s.split(/[.!؟!]/)[0]||s).slice(0,70)||'مشروع قصة'}
function labelCat(x){return({children:'أطفال',islamic:'إسلامية',religious:'دينية',educational:'تعليمية',moral:'تربوية',adventure:'مغامرات',historical:'تاريخية',fantasy:'خيال',social:'اجتماعية',science:'علمية',auto:'تلقائي'})[x]||'قصة'}
function install(){
  if(document.querySelector('[data-route="projects"]'))return;
  const nav=$('nav'),settings=nav?.querySelector('[data-route="settings"]'),b=document.createElement('button');b.className='nav-item';b.dataset.route='projects';b.innerHTML='<span>▣</span><div><b>مشاريعي</b><small>الفيديوهات والقصص المحفوظة</small></div>';settings?.insertAdjacentElement('beforebegin',b);
  const sec=document.createElement('section');sec.className='page';sec.dataset.page='projects';sec.innerHTML=`<div class="page-head"><div><span class="eyebrow">PROJECTS</span><h2>مشاريعي</h2><p>كل فيديو يتم إنشاؤه يُحفظ تلقائيًا على هذا الجهاز لتقدر ترجع له وتحمله مرة أخرى.</p></div><span id="projectsCount" class="health-pill">0 مشروع</span></div><div id="projectsGrid" class="projects38-grid"></div><div id="projectsEmpty" class="card projects38-empty">لا توجد مشاريع محفوظة حتى الآن.</div>`;document.querySelector('main.main')?.appendChild(sec);
  const st=document.createElement('style');st.textContent=`.projects38-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.p38{overflow:hidden}.p38-preview{aspect-ratio:16/9;background:#080d16;border-radius:14px;display:grid;place-items:center;overflow:hidden}.p38-preview video{width:100%;height:100%;object-fit:contain;background:#000}.p38 h3{font-size:18px;margin:12px 0 6px}.p38 p{opacity:.68;line-height:1.7;min-height:48px}.p38-meta{display:flex;gap:7px;flex-wrap:wrap;margin:10px 0}.p38-meta span{padding:5px 8px;border-radius:8px;background:rgba(255,255,255,.05);font-size:12px}.p38-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.p38-actions>*{flex:1;min-width:100px;text-align:center}.projects38-empty{text-align:center;padding:34px;opacity:.7}@media(max-width:900px){.projects38-grid{grid-template-columns:1fr}}`;document.head.appendChild(st);
}
async function cardFor(p){const blob=await getVideo(p.id),c=document.createElement('article');c.className='card p38';let src='';if(blob){src=URL.createObjectURL(blob);c.dataset.url=src}c.innerHTML=`<div class="p38-preview">${src?`<video controls playsinline preload="metadata" src="${src}"></video>`:'<span>لا توجد معاينة فيديو</span>'}</div><h3>${esc(p.title||titleOf(p))}</h3><p>${esc((p.story||'').slice(0,130))}${(p.story||'').length>130?'…':''}</p><div class="p38-meta"><span>${esc(labelCat(p.category))}</span><span>${p.format==='youtube'?'YouTube 16:9':'Short 9:16'}</span><span>${Math.round(Number(p.audioDuration)||0)} ثانية</span><span>${Number(p.sceneCount)||0} مشهد</span></div><small>آخر حفظ: ${esc(fmt(p.updatedAt||p.createdAt))}</small><div class="p38-actions"><button class="secondary" data-open>فتح المشروع</button>${blob?'<a class="primary" data-download download="reels-maker-project.webm">تحميل</a>':''}<button class="secondary" data-delete>حذف</button></div>`;
  if(blob)c.querySelector('[data-download]').href=src;
  c.querySelector('[data-open]')?.addEventListener('click',()=>openProject(p,blob));c.querySelector('[data-delete]')?.addEventListener('click',()=>removeProject(p.id));return c
}
async function render(){const grid=$('projectsGrid'),empty=$('projectsEmpty');if(!grid)return;grid.querySelectorAll('[data-url]').forEach(x=>{try{URL.revokeObjectURL(x.dataset.url)}catch{}});grid.innerHTML='';const list=read();$('projectsCount').textContent=`${list.length} مشروع`;empty.style.display=list.length?'none':'block';for(const p of list)grid.appendChild(await cardFor(p))}
function restoreSelect(id,val){const e=$(id);if(e&&[...e.options].some(o=>o.value===String(val)))e.value=String(val)}
async function openProject(p,blob){$('kidsIdea')&&( $('kidsIdea').value=p.idea||'' );$('kidsScript')&&( $('kidsScript').value=p.story||'' );restoreSelect('kidsDuration',p.duration);restoreSelect('kidsAge',p.audience);restoreSelect('kidsTone',p.tone);restoreSelect('kidsCategory',p.category);restoreSelect('kidsFormat',p.format);restoreSelect('kidsDialect',p.dialect);restoreSelect('kidsVoice',p.voice);if(blob){if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(blob);const v=$('kidsVideo'),d=$('kidsDownload');if(v)v.src=previewUrl;if(d){d.href=previewUrl;d.download=p.format==='youtube'?'reels-maker-youtube-story.webm':'reels-maker-short-story.webm'}$('kidsFinal')?.classList.remove('hidden');$('kidsProgressCard')?.classList.remove('hidden')}document.querySelector('[data-route="kids"]')?.click()}
async function removeProject(id){write(read().filter(x=>x.id!==id));await delVideo(id);render()}
async function save(detail,ready){if(!detail?.id)return;const now=Date.now(),list=read(),old=list.find(x=>x.id===detail.id),item={...(old||{}),...detail,title:titleOf(detail),createdAt:old?.createdAt||now,updatedAt:now,status:ready?'ready':'draft'};delete item.blob;write([item,...list.filter(x=>x.id!==detail.id)]);if(detail.blob)await putVideo(detail.id,detail.blob);render()}
export function initProjectsV38(){install();window.addEventListener('reels-project-draft',e=>save(e.detail,false));window.addEventListener('reels-project-ready',e=>save(e.detail,true));render()}
