const $=id=>document.getElementById(id);
const voices={egyptian:[['Sulafat','سلمى — دافئ'],['Gacrux','عمر — واضح'],['Kore','نور — ثابت'],['Schedar','كريم — هادئ']],gulf:[['Aoede','دانة — ناعم'],['Orus','راشد — واثق'],['Leda','ريم — شبابي'],['Puck','سلمان — حيوي']]};
const sample={egyptian:'كان الليل هادي، لكن يوسف حس إن الليلة دي مختلفة. فتح الباب بهدوء، وبدأت الحكاية.',gulf:'كانت الليلة هادئة، لكن راشد حس إن في شيء مختلف. فتح الباب بهدوء، ومن هنا بدأت الحكاية.'};
const state={story:'',audioBlob:null,audioUrl:'',audioDuration:0,scenes:[],sceneUrls:[],finalUrl:''};
function set(id,text){const e=$(id);if(e)e.textContent=text||''}
function fillVoice(select,dialect){const el=$(select);if(!el)return;el.innerHTML=voices[dialect].map(v=>`<option value="${v[0]}">${v[1]}</option>`).join('')}
function revoke(){if(state.audioUrl)URL.revokeObjectURL(state.audioUrl);if(state.finalUrl)URL.revokeObjectURL(state.finalUrl);state.sceneUrls.forEach(URL.revokeObjectURL);state.audioUrl='';state.finalUrl='';state.sceneUrls=[]}
async function jsonPost(url,data){const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||`HTTP ${r.status}`);return j}
async function tts(text,voice,dialect,tone){const r=await fetch('/api/tts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text,voice,dialect,tone})});if(!r.ok){const j=await r.json().catch(()=>({}));throw new Error(j.error||`TTS ${r.status}`)}return r.blob()}
async function durationOf(blob){const u=URL.createObjectURL(blob),a=new Audio(u);const d=await new Promise(resolve=>{let done=false;const end=()=>{if(done)return;done=true;resolve(Number.isFinite(a.duration)?a.duration:0)};a.onloadedmetadata=end;a.onerror=end;setTimeout(end,5000)});URL.revokeObjectURL(u);return d}
function pipe(name){const all=[...document.querySelectorAll('.pipe')],i=all.findIndex(x=>x.dataset.step===name);all.forEach((x,n)=>{x.classList.toggle('active',n===i);x.classList.toggle('done',n<i)})}
async function preview(selectDialect,selectVoice,audio,status){const d=$(selectDialect).value,v=$(selectVoice).value;set(status,'جاري إنشاء عينة قصيرة...');try{const blob=await tts(sample[d],v,d,'natural'),u=URL.createObjectURL(blob),a=$(audio);if(a.dataset.url)URL.revokeObjectURL(a.dataset.url);a.dataset.url=u;a.src=u;a.classList.remove('hidden');await a.play().catch(()=>{});set(status,`تمت المعاينة · ${d==='egyptian'?'مصري':'خليجي'}`)}catch(e){set(status,'خطأ: '+e.message)}}
function renderScenes(){const host=$('sceneGrid');host.innerHTML='';state.scenes.forEach((s,i)=>{const d=document.createElement('div');d.className='scene';d.innerHTML=`<img src="${s.url}" alt="مشهد ${i+1}"><span>مشهد ${i+1}</span>`;host.appendChild(d)})}
async function generateImage(prompt,refs=[]){const fd=new FormData();fd.append('prompt',prompt);refs.slice(0,2).forEach((b,i)=>fd.append(`reference${i}`,b,`ref-${i}.jpg`));const r=await fetch('/api/image',{method:'POST',body:fd});if(!r.ok){const j=await r.json().catch(()=>({}));throw new Error(j.error||`Image ${r.status}`)}return r.blob()}
async function buildScenes(story,count){const j=await jsonPost('/api/story/scenes',{story,count}),out=[];for(let i=0;i<j.scenes.length;i++){set('storyStatus',`توليد الصورة ${i+1} من ${j.scenes.length}...`);const refs=i===0?[]:[out[0].blob,...(i>1?[out[i-1].blob]:[])],blob=await generateImage(j.scenes[i],refs),url=URL.createObjectURL(blob);state.sceneUrls.push(url);out.push({prompt:j.scenes[i],blob,url})}state.scenes=out;renderScenes()}
async function imageElements(){const out=[];for(const s of state.scenes){const img=new Image();img.src=s.url;await img.decode();out.push(img)}return out}
function drawCover(ctx,img,w,h,p,i,alpha=1){const sw=img.naturalWidth,sh=img.naturalHeight,base=Math.max(w/sw,h/sh),zoom=1.02+.07*(i%2?p:1-p),sc=base*zoom,dw=sw*sc,dh=sh*sc,dx=(w-dw)/2+(i%2?1:-1)*12*(p-.5),dy=(h-dh)/2;ctx.save();ctx.globalAlpha=alpha;ctx.drawImage(img,dx,dy,dw,dh);ctx.restore()}
async function renderVideo(){if(!window.MediaRecorder||!HTMLCanvasElement.prototype.captureStream)throw new Error('المتصفح لا يدعم الريندر المباشر');const AC=window.AudioContext||window.webkitAudioContext,ac=new AC();await ac.resume().catch(()=>{});const audio=await ac.decodeAudioData((await state.audioBlob.arrayBuffer()).slice(0)),total=audio.duration,imgs=await imageElements(),canvas=document.createElement('canvas');canvas.width=540;canvas.height=960;const ctx=canvas.getContext('2d',{alpha:false}),vs=canvas.captureStream(24),dest=ac.createMediaStreamDestination(),src=ac.createBufferSource();src.buffer=audio;src.connect(dest);const stream=new MediaStream([...vs.getVideoTracks(),...dest.stream.getAudioTracks()]),types=['video/webm;codecs=vp8,opus','video/webm'],mime=types.find(MediaRecorder.isTypeSupported.bind(MediaRecorder))||'',rec=new MediaRecorder(stream,mime?{mimeType:mime,videoBitsPerSecond:1800000,audioBitsPerSecond:128000}:{videoBitsPerSecond:1800000}),chunks=[];rec.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};const stopped=new Promise(r=>rec.onstop=r),per=total/imgs.length,fade=Math.min(.5,per*.12),start=performance.now();rec.start(1000);src.start();await new Promise(resolve=>{const tick=()=>{const t=(performance.now()-start)/1000;if(t>=total)return resolve();const i=Math.min(imgs.length-1,Math.floor(t/per)),local=t-i*per,p=Math.min(1,local/per);ctx.fillStyle='#000';ctx.fillRect(0,0,540,960);drawCover(ctx,imgs[i],540,960,p,i,1);if(i<imgs.length-1&&local>per-fade){const a=(local-(per-fade))/fade;drawCover(ctx,imgs[i+1],540,960,0,i+1,a)}set('storyStatus',`ريندر الفيديو ${Math.round(t)}/${Math.round(total)} ثانية...`);requestAnimationFrame(tick)};tick()});try{src.stop()}catch{}rec.stop();await stopped;ac.close().catch(()=>{});if(!chunks.length)throw new Error('لم ينتج ملف فيديو');return new Blob(chunks,{type:rec.mimeType||'video/webm'})}
async function runStory(){const idea=$('storyIdea').value.trim();if(!idea)return set('storyStatus','اكتب فكرة القصة أولًا.');const btn=$('generateStoryBtn'),duration=Number($('storyDuration').value),tone=$('storyTone').value,dialect=$('storyDialect').value,voice=$('storyVoice').value;btn.disabled=true;revoke();state.story='';state.audioBlob=null;state.scenes=[];$('sceneGrid').innerHTML='';$('finalWrap').classList.add('hidden');$('storyAudioWrap').classList.add('hidden');$('storyText').textContent='جاري كتابة القصة...';$('storyText').classList.remove('empty');try{pipe('story');set('storyStatus','1/4 كتابة قصة متماسكة بدون تكرار...');let j=await jsonPost('/api/story/generate',{idea,duration,tone});state.story=j.story;$('storyText').textContent=state.story;pipe('voice');set('storyStatus','2/4 إنشاء صوت الراوي المختار...');let blob=await tts(state.story,voice,dialect,tone),actual=await durationOf(blob);if(actual&&Math.abs(actual-duration)>5){set('storyStatus',`ضبط المدة ${Math.round(actual)} → ${duration} ثانية...`);const a=await jsonPost('/api/story/adjust',{story:state.story,currentDuration:actual,targetDuration:duration});state.story=a.story;$('storyText').textContent=state.story;blob=await tts(state.story,voice,dialect,tone);actual=await durationOf(blob)}state.audioBlob=blob;state.audioDuration=actual;state.audioUrl=URL.createObjectURL(blob);$('storyAudio').src=state.audioUrl;$('storyAudioWrap').classList.remove('hidden');set('storyAudioMeta',`${dialect==='egyptian'?'مصري':'خليجي'} · ${Math.round(actual)} ثانية · ${voice}`);pipe('scenes');const count=Math.max(5,Math.min(10,Math.ceil((actual||duration)/6)));set('storyStatus',`3/4 تقسيم القصة وتوليد ${count} صور مترابطة...`);await buildScenes(state.story,count);pipe('render');set('storyStatus','4/4 ريندر الفيديو النهائي...');const video=await renderVideo();state.finalUrl=URL.createObjectURL(video);$('finalVideo').src=state.finalUrl;$('downloadVideo').href=state.finalUrl;$('finalWrap').classList.remove('hidden');document.querySelectorAll('.pipe').forEach(x=>{x.classList.add('done');x.classList.remove('active')});set('storyStatus',`اكتمل · ${Math.round(actual)} ثانية · ${count} مشاهد`)}catch(e){set('storyStatus','خطأ: '+(e?.message||e))}finally{btn.disabled=false}}
export function initStoryStudio(){fillVoice('storyVoice','egyptian');$('storyDialect')?.addEventListener('change',e=>fillVoice('storyVoice',e.target.value));$('previewVoiceBtn')?.addEventListener('click',()=>preview('storyDialect','storyVoice','voicePreviewAudio','storyStatus'));$('generateStoryBtn')?.addEventListener('click',runStory)}
export function initVoiceStudio(){fillVoice('voiceName','egyptian');$('voiceDialect')?.addEventListener('change',e=>fillVoice('voiceName',e.target.value));$('voiceGenerateBtn')?.addEventListener('click',async()=>{const text=$('voiceText').value.trim(),d=$('voiceDialect').value,v=$('voiceName').value,btn=$('voiceGenerateBtn');if(!text)return set('voiceStatus','اكتب نصًا أولًا.');btn.disabled=true;set('voiceStatus','جاري توليد الصوت...');try{const blob=await tts(text,v,d,'natural'),u=URL.createObjectURL(blob),a=$('voiceAudio');if(a.dataset.url)URL.revokeObjectURL(a.dataset.url);a.dataset.url=u;a.src=u;a.classList.remove('hidden');set('voiceStatus',`جاهز · ${d==='egyptian'?'مصري':'خليجي'} · ${v}`)}catch(e){set('voiceStatus','خطأ: '+e.message)}finally{btn.disabled=false}})}