const $=id=>document.getElementById(id);
const fallbackVoices=[
{name:'Zephyr',style:'مشرق',gender:'female'},{name:'Puck',style:'حيوي',gender:'male'},{name:'Charon',style:'معلوماتي',gender:'male'},{name:'Kore',style:'ثابت',gender:'female'},{name:'Fenrir',style:'متحمس',gender:'male'},{name:'Leda',style:'شبابي',gender:'female'},{name:'Orus',style:'واثق',gender:'male'},{name:'Aoede',style:'خفيف',gender:'female'},{name:'Callirrhoe',style:'مريح',gender:'female'},{name:'Autonoe',style:'مشرق',gender:'female'},{name:'Enceladus',style:'هوائي',gender:'male'},{name:'Iapetus',style:'واضح',gender:'male'},{name:'Umbriel',style:'مريح',gender:'male'},{name:'Algieba',style:'ناعم',gender:'male'},{name:'Despina',style:'ناعم',gender:'female'},{name:'Erinome',style:'واضح',gender:'female'},{name:'Algenib',style:'خشن',gender:'male'},{name:'Rasalgethi',style:'معلوماتي',gender:'male'},{name:'Laomedeia',style:'حيوي',gender:'female'},{name:'Achernar',style:'ناعم',gender:'female'},{name:'Alnilam',style:'ثابت',gender:'male'},{name:'Schedar',style:'متزن',gender:'male'},{name:'Gacrux',style:'ناضج',gender:'female'},{name:'Pulcherrima',style:'مباشر',gender:'female'},{name:'Achird',style:'ودود',gender:'male'},{name:'Zubenelgenubi',style:'عفوي',gender:'male'},{name:'Vindemiatrix',style:'لطيف',gender:'female'},{name:'Sadachbia',style:'نشيط',gender:'male'},{name:'Sadaltager',style:'خبير',gender:'male'},{name:'Sulafat',style:'دافئ',gender:'female'}
];
const fallbackAccents=[
{id:'egyptian',label:'🇪🇬 مصري'},{id:'saudi',label:'🇸🇦 سعودي'},{id:'kuwaiti',label:'🇰🇼 كويتي'},{id:'emirati',label:'🇦🇪 إماراتي'},{id:'iraqi',label:'🇮🇶 عراقي'},{id:'qatari',label:'🇶🇦 قطري'},{id:'bahraini',label:'🇧🇭 بحريني'},{id:'omani',label:'🇴🇲 عُماني'},{id:'gulf',label:'🌍 خليجي عام'}
];
const recommended={male:['Charon','Orus','Iapetus','Schedar','Achird','Sadaltager','Rasalgethi','Puck'],female:['Sulafat','Kore','Zephyr','Aoede','Gacrux','Leda','Vindemiatrix','Laomedeia']};
const sample={
 egyptian:'كان الليل هادي، لكن يوسف حس إن الليلة دي مختلفة. فتح الباب بهدوء، وبدأت الحكاية.',
 saudi:'كانت الليلة هادئة، لكن سعود حس إن هالليلة فيها شيء مختلف. فتح الباب بهدوء، ومن هنا بدأت الحكاية.',
 kuwaiti:'كانت الليلة هادية، بس فهد حس إن هالليلة غير. فتح الباب بهدوء، ومن هني بدت الحكاية.',
 emirati:'كانت الليلة هادية، لكن راشد حس إن هالليلة غير. فتح الباب بهدوء، ومن هني بدت السالفة.',
 iraqi:'كانت الليلة هادئة، بس علي حس إن هالليلة بيها شي مختلف. فتح الباب بهدوء، ومن هنا بدت الحكاية.',
 qatari:'كانت الليلة هادية، لكن حمد حس إن هالليلة فيها شيء مختلف. فتح الباب بهدوء، ومن هني بدت الحكاية.',
 bahraini:'كانت الليلة هادية، بس سلمان حس إن هالليلة غير. فتح الباب بهدوء، ومن هني بدت الحكاية.',
 omani:'كانت الليلة هادئة، لكن سالم حس إن هالليلة فيها شيء مختلف. فتح الباب بهدوء، ومن هنا بدت الحكاية.',
 gulf:'كانت الليلة هادئة، لكن راشد حس إن في شيء مختلف. فتح الباب بهدوء، ومن هنا بدأت الحكاية.'
};
const state={voiceCatalog:fallbackVoices,accents:fallbackAccents,story:'',audioBlob:null,audioUrl:'',audioDuration:0,scenes:[],sceneUrls:[],finalUrl:''};
function set(id,text){const e=$(id);if(e)e.textContent=text||''}
function accentLabel(id){return state.accents.find(x=>x.id===id)?.label||id}
async function loadVoiceCatalog(){try{const r=await fetch('/api/voices',{cache:'no-store'}),j=await r.json();if(r.ok&&Array.isArray(j.voices)&&j.voices.length)state.voiceCatalog=j.voices.map(v=>({name:v.name,style:v.style||'صوت AI',gender:v.gender||'male'}));if(r.ok&&Array.isArray(j.accents)&&j.accents.length)state.accents=j.accents}catch{}return state.voiceCatalog}
function fillAccent(select){const el=$(select);if(el)el.innerHTML=state.accents.map(x=>`<option value="${x.id}">${x.label}</option>`).join('')}
function ensureGenderSelect(anchorId,newId){if($(newId))return;const anchor=$(anchorId);if(!anchor)return;const parent=anchor.closest('label');if(!parent)return;const label=document.createElement('label');label.innerHTML=`نوع الصوت<select id="${newId}"><option value="all">الكل</option><option value="male">رجال</option><option value="female">نساء</option></select>`;parent.insertAdjacentElement('afterend',label)}
function fillVoice(select,gender='all'){const el=$(select);if(!el)return;const filtered=gender==='all'?state.voiceCatalog:state.voiceCatalog.filter(v=>v.gender===gender);const men=filtered.filter(v=>v.gender==='male'),women=filtered.filter(v=>v.gender==='female');const sort=(arr,g)=>arr.slice().sort((a,b)=>{const ai=recommended[g].indexOf(a.name),bi=recommended[g].indexOf(b.name);return (ai<0?99:ai)-(bi<0?99:bi)});const groups=[];if(men.length)groups.push(`<optgroup label="رجال (${men.length})">${sort(men,'male').map(v=>`<option value="${v.name}">👨 ${v.name} — ${v.style}</option>`).join('')}</optgroup>`);if(women.length)groups.push(`<optgroup label="نساء (${women.length})">${sort(women,'female').map(v=>`<option value="${v.name}">👩 ${v.name} — ${v.style}</option>`).join('')}</optgroup>`);el.innerHTML=groups.join('')}
function setupVoiceControls(accentId,voiceId,genderId){fillAccent(accentId);ensureGenderSelect(accentId,genderId);fillVoice(voiceId,'all');$(genderId)?.addEventListener('change',e=>fillVoice(voiceId,e.target.value))}
function revoke(){if(state.audioUrl)URL.revokeObjectURL(state.audioUrl);if(state.finalUrl)URL.revokeObjectURL(state.finalUrl);state.sceneUrls.forEach(u=>{try{URL.revokeObjectURL(u)}catch{}});state.audioUrl='';state.finalUrl='';state.sceneUrls=[]}
async function jsonPost(url,data){const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||`HTTP ${r.status}`);return j}
async function tts(text,voice,accent,tone){const r=await fetch('/api/tts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text,voice,dialect:accent,tone})});if(!r.ok){const j=await r.json().catch(()=>({}));throw new Error(j.error||`TTS ${r.status}`)}const blob=await r.blob();if(!blob.size)throw new Error('لم يرجع ملف صوت');return blob}
async function durationOf(blob){const u=URL.createObjectURL(blob),a=new Audio(u);const d=await new Promise(resolve=>{let done=false;const end=()=>{if(done)return;done=true;resolve(Number.isFinite(a.duration)?a.duration:0)};a.onloadedmetadata=end;a.onerror=end;setTimeout(end,5000)});URL.revokeObjectURL(u);return d}
function pipe(name){const all=[...document.querySelectorAll('.pipe')],i=all.findIndex(x=>x.dataset.step===name);all.forEach((x,n)=>{x.classList.toggle('active',n===i);x.classList.toggle('done',n<i)})}
async function preview(selectAccent,selectVoice,audio,status){const d=$(selectAccent).value,v=$(selectVoice).value,a=$(audio);set(status,`جاري إنشاء عينة ${accentLabel(d)} بصوت ${v}...`);try{const blob=await tts(sample[d]||sample.gulf,v,d,'natural'),u=URL.createObjectURL(blob);if(a.dataset.url)URL.revokeObjectURL(a.dataset.url);a.dataset.url=u;a.src=u;a.classList.remove('hidden');a.load();await a.play().catch(()=>{});set(status,`العينة جاهزة · ${accentLabel(d)} · ${v}`)}catch(e){set(status,'خطأ الصوت: '+e.message)}}
function renderScenes(){const host=$('sceneGrid');host.innerHTML='';state.scenes.forEach((s,i)=>{const d=document.createElement('div');d.className='scene';d.innerHTML=`<img src="${s.url}" alt="مشهد ${i+1}"><span>مشهد ${i+1}</span>`;host.appendChild(d)})}
async function generateImage(prompt,refs=[]){const fd=new FormData();fd.append('prompt',prompt);refs.slice(0,2).forEach((b,i)=>fd.append(`reference${i}`,b,`ref-${i}.jpg`));const r=await fetch('/api/image',{method:'POST',body:fd});if(!r.ok){const j=await r.json().catch(()=>({}));throw new Error(j.error||`Image ${r.status}`)}return r.blob()}
async function buildScenes(story,count){const j=await jsonPost('/api/story/scenes',{story,count}),out=[];for(let i=0;i<j.scenes.length;i++){set('storyStatus',`توليد الصورة ${i+1} من ${j.scenes.length}...`);const refs=i===0?[]:[out[0].blob,...(i>1?[out[i-1].blob]:[])],blob=await generateImage(j.scenes[i],refs),url=URL.createObjectURL(blob);state.sceneUrls.push(url);out.push({prompt:j.scenes[i],blob,url})}state.scenes=out;renderScenes()}
async function imageElements(){const out=[];for(const s of state.scenes){const img=new Image();img.src=s.url;await img.decode();out.push(img)}return out}
function drawCover(ctx,img,w,h,p,i,alpha=1){const sw=img.naturalWidth,sh=img.naturalHeight,base=Math.max(w/sw,h/sh),zoom=1.02+.07*(i%2?p:1-p),sc=base*zoom,dw=sw*sc,dh=sh*sc,dx=(w-dw)/2+(i%2?1:-1)*12*(p-.5),dy=(h-dh)/2;ctx.save();ctx.globalAlpha=alpha;ctx.drawImage(img,dx,dy,dw,dh);ctx.restore()}
async function renderVideo(){if(!window.MediaRecorder||!HTMLCanvasElement.prototype.captureStream)throw new Error('المتصفح لا يدعم الريندر المباشر');const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw new Error('AudioContext غير مدعوم');const ac=new AC();await ac.resume().catch(()=>{});const audio=await ac.decodeAudioData((await state.audioBlob.arrayBuffer()).slice(0)),total=audio.duration,imgs=await imageElements(),canvas=document.createElement('canvas');canvas.width=540;canvas.height=960;const ctx=canvas.getContext('2d',{alpha:false}),vs=canvas.captureStream(24),dest=ac.createMediaStreamDestination(),src=ac.createBufferSource();src.buffer=audio;src.connect(dest);const stream=new MediaStream([...vs.getVideoTracks(),...dest.stream.getAudioTracks()]),types=['video/webm;codecs=vp8,opus','video/webm'],mime=types.find(x=>MediaRecorder.isTypeSupported(x))||'',rec=new MediaRecorder(stream,mime?{mimeType:mime,videoBitsPerSecond:1800000,audioBitsPerSecond:128000}:{videoBitsPerSecond:1800000}),chunks=[];rec.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};const stopped=new Promise(r=>rec.onstop=r),per=total/imgs.length,fade=Math.min(.5,per*.12),start=performance.now();rec.start(1000);src.start();await new Promise(resolve=>{const tick=()=>{const t=(performance.now()-start)/1000;if(t>=total)return resolve();const i=Math.min(imgs.length-1,Math.floor(t/per)),local=t-i*per,p=Math.min(1,local/per);ctx.fillStyle='#000';ctx.fillRect(0,0,540,960);drawCover(ctx,imgs[i],540,960,p,i,1);if(i<imgs.length-1&&local>per-fade){const a=(local-(per-fade))/fade;drawCover(ctx,imgs[i+1],540,960,0,i+1,a)}set('storyStatus',`ريندر الفيديو ${Math.round(t)}/${Math.round(total)} ثانية...`);requestAnimationFrame(tick)};tick()});try{src.stop()}catch{}rec.stop();await stopped;ac.close().catch(()=>{});if(!chunks.length)throw new Error('لم ينتج ملف فيديو');return new Blob(chunks,{type:rec.mimeType||'video/webm'})}
async function runStory(){const idea=$('storyIdea').value.trim();if(!idea)return set('storyStatus','اكتب فكرة القصة أولًا.');const btn=$('generateStoryBtn'),duration=Number($('storyDuration').value),tone=$('storyTone').value,accent=$('storyDialect').value,voice=$('storyVoice').value;btn.disabled=true;revoke();state.story='';state.audioBlob=null;state.scenes=[];$('sceneGrid').innerHTML='';$('finalWrap').classList.add('hidden');$('storyAudioWrap').classList.add('hidden');$('storyText').textContent='جاري كتابة القصة...';$('storyText').classList.remove('empty');try{pipe('story');set('storyStatus','1/4 كتابة قصة متماسكة بدون تكرار...');let j=await jsonPost('/api/story/generate',{idea,duration,tone});state.story=j.story;$('storyText').textContent=state.story;pipe('voice');set('storyStatus',`2/4 إنشاء صوت الراوي ${voice} · ${accentLabel(accent)}...`);let blob=await tts(state.story,voice,accent,tone),actual=await durationOf(blob);if(actual&&Math.abs(actual-duration)>5){set('storyStatus',`ضبط المدة ${Math.round(actual)} → ${duration} ثانية...`);const a=await jsonPost('/api/story/adjust',{story:state.story,currentDuration:actual,targetDuration:duration});state.story=a.story;$('storyText').textContent=state.story;blob=await tts(state.story,voice,accent,tone);actual=await durationOf(blob)}state.audioBlob=blob;state.audioDuration=actual;state.audioUrl=URL.createObjectURL(blob);$('storyAudio').src=state.audioUrl;$('storyAudioWrap').classList.remove('hidden');set('storyAudioMeta',`${accentLabel(accent)} · ${Math.round(actual)} ثانية · ${voice}`);pipe('scenes');const count=Math.max(5,Math.min(10,Math.ceil((actual||duration)/6)));set('storyStatus',`3/4 تقسيم القصة وتوليد ${count} صور مترابطة...`);await buildScenes(state.story,count);pipe('render');set('storyStatus','4/4 ريندر الفيديو النهائي...');const video=await renderVideo();state.finalUrl=URL.createObjectURL(video);$('finalVideo').src=state.finalUrl;$('downloadVideo').href=state.finalUrl;$('finalWrap').classList.remove('hidden');document.querySelectorAll('.pipe').forEach(x=>{x.classList.add('done');x.classList.remove('active')});set('storyStatus',`اكتمل · ${Math.round(actual)} ثانية · ${count} مشاهد`)}catch(e){set('storyStatus','خطأ: '+(e?.message||e))}finally{btn.disabled=false}}
export async function initStoryStudio(){await loadVoiceCatalog();setupVoiceControls('storyDialect','storyVoice','storyGender');$('previewVoiceBtn')?.addEventListener('click',()=>preview('storyDialect','storyVoice','voicePreviewAudio','storyStatus'));$('generateStoryBtn')?.addEventListener('click',runStory)}
export async function initVoiceStudio(){await loadVoiceCatalog();setupVoiceControls('voiceDialect','voiceName','voiceGender');$('voiceGenerateBtn')?.addEventListener('click',async()=>{const text=$('voiceText').value.trim(),d=$('voiceDialect').value,v=$('voiceName').value,btn=$('voiceGenerateBtn');if(!text)return set('voiceStatus','اكتب نصًا أولًا.');btn.disabled=true;set('voiceStatus',`جاري توليد ${accentLabel(d)} بصوت ${v}...`);try{const blob=await tts(text,v,d,'natural'),u=URL.createObjectURL(blob),a=$('voiceAudio');if(a.dataset.url)URL.revokeObjectURL(a.dataset.url);a.dataset.url=u;a.src=u;a.classList.remove('hidden');a.load();await a.play().catch(()=>{});set('voiceStatus',`جاهز · ${accentLabel(d)} · ${v}`)}catch(e){set('voiceStatus','خطأ الصوت: '+e.message)}finally{btn.disabled=false}})}
