import baseWorker from "./worker-v11.js";

const CF_TEXT_MODELS=["@cf/zai-org/glm-4.7-flash","@cf/google/gemma-4-26b-a4b-it"];
const TTS_MODELS=["gemini-3.1-flash-tts-preview","gemini-2.5-flash-preview-tts"];
const TTS_VOICES=new Set(["Kore","Charon","Aoede","Puck","Zephyr","Fenrir"]);
function decodeBase64(data){const binary=atob(String(data||"").replace(/\s/g,"")),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes;}
function pcm16ToWav(pcm,sampleRate=24000){const b=new ArrayBuffer(44+pcm.byteLength),v=new DataView(b),w=(o,t)=>{for(let i=0;i<t.length;i++)v.setUint8(o+i,t.charCodeAt(i));};w(0,"RIFF");v.setUint32(4,36+pcm.byteLength,true);w(8,"WAVE");w(12,"fmt ");v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,sampleRate,true);v.setUint32(28,sampleRate*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);w(36,"data");v.setUint32(40,pcm.byteLength,true);new Uint8Array(b,44).set(pcm);return new Uint8Array(b);}
async function expressiveStoryVoice(request,env,ctx){
  if(!env.GEMINI_API_KEY)return baseWorker.fetch(request,env,ctx);
  const body=await safeJson(request.clone()),text=clean(body.text,6000);if(!text)return baseWorker.fetch(request,env,ctx);const voice=TTS_VOICES.has(body.voice)?body.voice:"Kore";
  const direction=`Narrate this Arabic story as a skilled human storyteller who is emotionally inside the scene, not as someone reading text. Infer the emotion sentence by sentence. Suspense: slightly slower, lower and more controlled with a short pause before the reveal. Surprise: a natural lift in energy, never shouting. Sad or tender moments: softer and warmer. Dialogue: subtly distinguish quoted speech while keeping one narrator identity. Important words may receive gentle emphasis. Vary rhythm naturally, use meaningful pauses at punctuation, avoid robotic equal pacing, avoid exaggerated acting, and never speak these instructions. Read the Arabic transcript exactly without adding or omitting words.`;
  for(const model of TTS_MODELS){try{const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:"POST",headers:{"x-goog-api-key":env.GEMINI_API_KEY,"content-type":"application/json"},body:JSON.stringify({contents:[{parts:[{text:`${direction}\n\nArabic transcript:\n${text}`}]}],generationConfig:{responseModalities:["AUDIO"],speechConfig:{languageCode:"ar-XA",voiceConfig:{prebuiltVoiceConfig:{voiceName:voice}}}}})});const d=await r.json().catch(()=>({}));if(!r.ok)continue;const part=d?.candidates?.[0]?.content?.parts?.find(x=>x?.inlineData?.data);if(!part?.inlineData?.data)continue;const raw=decodeBase64(part.inlineData.data),mime=String(part.inlineData.mimeType||"audio/L16;codec=pcm;rate=24000"),bytes=mime.toLowerCase().includes("wav")?raw:pcm16ToWav(raw,24000);return new Response(bytes,{headers:{"content-type":mime.toLowerCase().includes("wav")?mime:"audio/wav","cache-control":"no-store","x-story-voice":"expressive-v4","x-gemini-tts-model":model}});}catch{}}
  return baseWorker.fetch(request,env,ctx);
}

function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store","access-control-allow-origin":"*",...headers}});}
async function safeJson(request){try{return await request.json();}catch{return{};}}
function clean(v,max=5000){return String(v||"").trim().slice(0,max);}
function extractText(result){if(!result)return"";if(typeof result==="string")return result.trim();if(typeof result.response==="string")return result.response.trim();if(typeof result.result==="string")return result.result.trim();if(typeof result.output_text==="string")return result.output_text.trim();const c=result.choices?.[0];if(typeof c?.message?.content==="string")return c.message.content.trim();if(Array.isArray(c?.message?.content))return c.message.content.map(x=>x?.text||x?.content||"").join("\n").trim();return"";}
async function workersText(env,system,prompt,maxTokens=900,temperature=.62){if(!env.AI?.run)return null;for(const model of CF_TEXT_MODELS){try{const result=await env.AI.run(model,{messages:[{role:"system",content:system},{role:"user",content:prompt}],max_completion_tokens:maxTokens,temperature,stream:false,chat_template_kwargs:{enable_thinking:false}});const text=extractText(result);if(text)return{text,model};}catch{}}return null;}

function fallbackContinuation(previous,part,total){const tail=clean(previous,1200).split(/(?<=[.!؟])\s+/).slice(-3).join(" ");if(part>=total)return `استمرت الأحداث مباشرة من اللحظة الأخيرة. ${tail}\n\nوبعد أن ظهرت الحقيقة كاملة، واجه البطل الموقف بشجاعة، وفهم سبب كل ما حدث من البداية. لم تكن النهاية كما توقع، لكنها كشفت له أن الحكم السريع قد يغير معنى القصة كلها. وبعد حوار صادق بين الشخصيات، انتهى الخلاف واتضحت الحقيقة، وبقي الدرس الأهم: لا تحكم على القصة من نصفها.\n\nالنهاية.`;return `استمرت الأحداث من نفس اللحظة التي انتهى عندها الجزء السابق. ${tail}\n\nحاول البطل أن يفهم ما يحدث من دون أن يكشف أنه عرف الحقيقة، لكن تصرفًا صغيرًا من الشخصية الأخرى جعله يشك أكثر. بدأ يتتبع التفاصيل، وربط بين الكلمات القديمة وما رآه أمامه، حتى وصل إلى دليل لم يكن يتوقع وجوده. وعندما مد يده إليه، سمع جملة واحدة قلبت فهمه لكل ما سبق.\n\nلكن الحقيقة الكاملة ما زالت مخفية...\nانتظرونا في الجزء ${part+1}${part+1===total?" والأخير":""}...`;}

async function storyContinue(request,env){const body=await safeJson(request);const previous=clean(body.previousStory,12000);if(!previous)return json({error:"لا يوجد جزء سابق لتكملة القصة."},400);const part=Math.max(2,Number(body.part)||2),total=Math.max(part,Number(body.total)||3),topic=clean(body.topic,180)||"قصة عربية";const chars=Array.isArray(body.characters)?body.characters.filter(x=>x?.name).slice(0,8):[];const characterText=chars.length?chars.map(c=>`- ${clean(c.name,60)}: ${clean(c.role,100)} ${clean(c.notes,220)}`).join("\n"):"- حافظ على الشخصيات الموجودة في النص السابق ولا تضف شخصية رئيسية جديدة بلا ضرورة.";const ending=part<total?`اختم بلحظة تشويق قوية ثم اكتب حرفيًا: انتظرونا في الجزء ${part+1}${part+1===total?" والأخير":""}...`:`اختم القصة بحل واضح ومؤثر ثم اكتب: النهاية.`;const prompt=`اكتب الجزء ${part} من ${total} من نفس القصة العربية التالية، وليس قصة جديدة.\nالموضوع: ${topic}\n\nالجزء السابق:\n${previous}\n\nالشخصيات الثابتة:\n${characterText}\n\nالشروط:\n- ابدأ مباشرة من آخر حدث في الجزء السابق، بلا إعادة مقدمة.\n- حافظ على نفس أسماء الشخصيات وعلاقاتها وملابسها وصفاتها المنطقية.\n- المدة المستهدفة نحو 40 إلى 50 ثانية، تقريبًا 95 إلى 130 كلمة.\n- اكتب مشاهد بصرية واضحة قابلة للتحويل إلى فيديو.\n- اجعل الإيقاع متصاعدًا وطبيعيًا، مع حوار قليل ومؤثر.\n- لا تخترع آيات أو أحاديث أو تنسب قولًا دينيًا لمصدر.\n- ${ending}\n- أعد النص النهائي بالعربية فقط، بلا شرح أو عناوين تحليلية.`;const out=await workersText(env,"أنت كاتب سلاسل قصص قصيرة للفيديو. مهمتك الحفاظ الصارم على الاستمرارية بين الأجزاء.",prompt,900,.7);return json({text:out?.text||fallbackContinuation(previous,part,total),part,total,model:out?.model||"local-continuation"});}

async function strictImage(request,env,ctx){const body=await safeJson(request.clone());const original=clean(body.prompt,2200);if(!original)return baseWorker.fetch(request,env,ctx);const strict=`Follow the user's description LITERALLY. The requested subject, number of people, action, setting, camera view and mood are mandatory. Do not replace the requested scene with symbolic, abstract, unrelated or generic imagery. Do not add extra people or objects unless required. If named/defined characters are present, preserve their identity and roles exactly. User request: ${original}`;const nanoReq=new Request(request.url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...body,prompt:strict,provider:"nano"})});const nano=await baseWorker.fetch(nanoReq,env,ctx);if(nano.ok)return nano;const fallbackReq=new Request(request.url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...body,prompt:strict,provider:"auto"})});return baseWorker.fetch(fallbackReq,env,ctx);}

async function injectV12(response){const type=response.headers.get("content-type")||"";if(!type.includes("text/html"))return response;let html=await response.text();html=html.replace(/story-director-v4\.css\?v=\d+/g,"story-director-v4.css?v=1");html=html.replace(/story-director-v4\.js\?v=\d+/g,"story-director-v4.js?v=1");if(!html.includes("story-director-v4.css"))html=html.replace("</head>",'<link rel="stylesheet" href="story-director-v4.css?v=1"></head>');if(!html.includes("story-director-v4.js"))html=html.replace("</body>",'<script src="story-director-v4.js?v=1"></script></body>');const headers=new Headers(response.headers);headers.delete("content-length");headers.set("cache-control","no-store");return new Response(html,{status:response.status,statusText:response.statusText,headers});}

export default{async fetch(request,env,ctx){const url=new URL(request.url);if(url.pathname==="/api/story-continue"&&request.method==="POST")return storyContinue(request,env);if(url.pathname==="/api/story-voice"&&request.method==="POST")return expressiveStoryVoice(request,env,ctx);if(url.pathname==="/api/image-studio"&&request.method==="POST")return strictImage(request,env,ctx);const response=await baseWorker.fetch(request,env,ctx);return injectV12(response);}};